export const headerMenu = {
  manu: [
    { name: 'Home', url: '/' },
    { name: 'About', url: '/about' },
    {
      name: 'Product',
      url: '/vehicles',
      children: [
        { name: 'Fateh Diamond MS', slug: 'fateh-diamond-ms', },
        { name: 'Fateh Diamond SS', slug: 'fateh-diamond-ss', },
        { name: 'Fateh Silver MS', slug: 'fateh-silver-ms', },
        { name: 'Fateh Silver SS', slug: 'fateh-silver-ss', },
      ],
    },
    { name: 'Gallery', url: '/gallery' },
    { name: 'Contact', url: '/contact' },
  ],
  button: {
    name: 'Dealership',
    url: '/dealership',
  },
};



export const herobarData = [
  {
    subTitle: 'Welcome To FatehEV',
    title: 'Your Best New Eco-Friendly Ride With FatehEV',
    image: '/images/herobar/Slider01.jpg',
    bgImage: '/images/herobar/bg1.webp',
  },
  {
    subTitle: 'Welcome To FatehEV',
    title: 'Your Best New Eco-Friendly Ride With FatehEV',
    image: '/images/herobar/Slider02.jpg',
    bgImage: '/images/herobar/bg1.webp',
  },
];



export const productData = [
  {
    name: 'Fateh Diamond MS',
    image: '',
    featuredImage: '/images/diamond ms/fateh-diamond-ms.jpg',
    gallery: ['/images/products/product-2.webp'],
    description:
      'The epitome of performance and reliability, the FatehEV Pro is our premium offering, equipped with advanced features for those who seek the best.',
    slug: 'fateh-diamond-ms',
    features: {
      overview: [
        {
          icon: 'fluent:paint-brush-32-filled',
          name: 'PU PAINT WITH LONG LASTING 5 COAT',
        },
        {
          icon: 'fluent:wrench-screwdriver-32-filled',
          name: 'UNIQUE RICH DESIGN',
        },
        {
          icon: 'ic:baseline-electric-rickshaw',
          name: 'IN ROOF HITLON AND CLOTH',
        },
        { icon: 'material-symbols:speed', name: 'HIGH PICKUP AND SPEED' },
        { icon: 'material-symbols:support', name: 'DOUBLE NECK SUPPORT' },
        { icon: 'game-icons:spring', name: 'REAR SHOCKERS' },
        { icon: 'ix:device-driver', name: 'CENTER LOCKING WITH BREAK JAMMING' },
        {
          icon: 'line-md:car-light',
          name: 'LED INDICATORS WITH NEW TRANSPERENT DESIGN',
        },
        {
          icon: 'ph:seat-fill',
          name: 'MACHINERY MADE WIDDER SEATS FOR BEST COMFORT',
        },
        {
          icon: 'eos-icons:performance',
          name: '10 MM WIRRING FOR BEST PERFORMANCE',
        },
        {
          icon: 'icon-park-solid:handle-round',
          name: 'BEST HANDLE CUTTING FOR EASY DRIVE',
        },
      ],
      specification: [
        {
          mileage: '100-150 Km (As per Battery Fittment)',
          batteryType: 'Lead Acid/Li-Ion',
          batteryWarranty: '1 To 3 Year (As Per Requirement),',
          motorAndController: '1100W/1250W',
          chargingTime: '6-8 Hours',
          sittingCapacity: '1 + 4 Person',
          brake: 'Brake Drum',
          speedometer: 'Digital',
          tyres: 'CEAT/Ralco',
          chassisWarranty: '1 Year',
          shockers: `31' Heavy Duty`,
          seat: 'Machinery Made Foam',
        },
      ],
      info: [
        'HEAVY DUTY CHASSIS & BODY',
        '5 COAT LONG LASTING PAINT',
        'UNIQUE RICH DESIGN',
        `HEAVY DUTY 31' SHOCKERS`,
        `MOBILE CHARGER`,
        `MOBILE HOLDER`,
        `DIGITAL METER`,
        `IN ROOF HITLON CLOTH`,
        `CAN GIVE MILEAGE UPTO 100 TO 150 KMS (AS PER BATTERY FITMENT)`,
        `HIGH PCKUP AND SPEED`,
        `DOUBLE NECK SUPPORT`,
        `REAR SHOCKERS`,
        `CENTER LOCKINGWITH BREAK JAMMING`,
        `GPS TRACKING (ON DEMAND)`,
        `FRONT MIRROR LIGHT`,
        `BATTERY WARRANTY UPTO 3 YEARS`,
        `FULL CHARGE IN 6 HOURS`,
        `LED INDICATOR WITH NEW DESIGN`,
        `MACHINERY MADE WIDER SEATS FOR BEST COMFORT`,
        `PURE 10MM WIRRING FOR BEST PERFORMANCE`,
        `BEST HANDLE CUTTING FOR EASY DRIVE`,
      ],
    },
  },
  {
    name: 'Fateh Diamond SS',
    image: '',
    featuredImage: '/images/diamond ss/fateh-diamond-ss.jpg',
    // gallery: ['/images/products/product-2.webp'],
    gallery: ['/images/diamond ss/fateh-diamond-ss-black.png',
      '/images/diamond ss/fateh-diamond-ss-green.png',
      '/images/diamond ss/fateh-diamond-ss-lightgreen.png',
      '/images/diamond ss/fateh-diamond-ss-purple.png',
      '/images/diamond ss/fateh-diamond-ss-red.png',
    ],
    description:
      'The epitome of performance and reliability, the FatehEV Pro is our premium offering, equipped with advanced features for those who seek the best.',
    slug: 'fateh-diamond-ss',
    features: {
      overview: [
        {
          icon: 'fluent:paint-brush-32-filled',
          name: 'PU PAINT WITH LONG LASTING 5 COAT',
        },
        {
          icon: 'fluent:wrench-screwdriver-32-filled',
          name: 'UNIQUE RICH DESIGN',
        },
        {
          icon: 'ic:baseline-electric-rickshaw',
          name: 'IN ROOF HITLON AND CLOTH',
        },
        { icon: 'material-symbols:speed', name: 'HIGH PICKUP AND SPEED' },
        { icon: 'material-symbols:support', name: 'DOUBLE NECK SUPPORT' },
        { icon: 'game-icons:spring', name: 'REAR SHOCKERS' },
        { icon: 'ix:device-driver', name: 'CENTER LOCKING WITH BREAK JAMMING' },
        {
          icon: 'line-md:car-light',
          name: 'LED INDICATORS WITH NEW TRANSPERENT DESIGN',
        },
        {
          icon: 'ph:seat-fill',
          name: 'MACHINERY MADE WIDDER SEATS FOR BEST COMFORT',
        },
        {
          icon: 'eos-icons:performance',
          name: '10 MM WIRRING FOR BEST PERFORMANCE',
        },
        {
          icon: 'icon-park-solid:handle-round',
          name: 'BEST HANDLE CUTTING FOR EASY DRIVE',
        },
      ],
      specification: [
        {
          mileage: '100-150 Km (As per Battery Fittment)',
          batteryType: 'Lead Acid/Li-Ion',
          batteryWarranty: '1 To 3 Year (As Per Requirement),',
          motorAndController: '1100W/1250W',
          chargingTime: '6-8 Hours',
          sittingCapacity: '1 + 4 Person',
          brake: 'Brake Drum',
          speedometer: 'Digital',
          tyres: 'CEAT/Ralco',
          chassisWarranty: '1 Year',
          shockers: `31' Heavy Duty`,
          seat: 'Machinery Made Foam',
        },
      ],
      info: [
        'HEAVY DUTY CHASSIS & BODY',
        '5 COAT LONG LASTING PAINT',
        'UNIQUE RICH DESIGN',
        `HEAVY DUTY 31' SHOCKERS`,
        `MOBILE CHARGER`,
        `MOBILE HOLDER`,
        `DIGITAL METER`,
        `IN ROOF HITLON CLOTH`,
        `CAN GIVE MILEAGE UPTO 100 TO 150 KMS (AS PER BATTERY FITMENT)`,
        `HIGH PCKUP AND SPEED`,
        `DOUBLE NECK SUPPORT`,
        `REAR SHOCKERS`,
        `CENTER LOCKINGWITH BREAK JAMMING`,
        `GPS TRACKING (ON DEMAND)`,
        `FRONT MIRROR LIGHT`,
        `BATTERY WARRANTY UPTO 3 YEARS`,
        `FULL CHARGE IN 6 HOURS`,
        `LED INDICATOR WITH NEW DESIGN`,
        `MACHINERY MADE WIDER SEATS FOR BEST COMFORT`,
        `PURE 10MM WIRRING FOR BEST PERFORMANCE`,
        `BEST HANDLE CUTTING FOR EASY DRIVE`,
      ],
    },
  },
  {
    name: 'Fateh Silver MS',
    image: '',
    featuredImage: '/images/silver ms/fateh-silver-ms.jpg',
    description:
      'Perfect for budget-conscious buyers, this model balances cost with efficiency, making it an excellent choice for everyday use.',
    slug: 'fateh-silver-ms',
    features: {
      overview: [
        {
          icon: 'fluent:paint-brush-32-filled',
          name: 'PU PAINT WITH LONG LASTING 5 COAT',
        },
        {
          icon: 'fluent:wrench-screwdriver-32-filled',
          name: 'UNIQUE RICH DESIGN',
        },
        {
          icon: 'ic:baseline-electric-rickshaw',
          name: 'IN ROOF HITLON AND CLOTH',
        },
        { icon: 'material-symbols:speed', name: 'HIGH PICKUP AND SPEED' },
        { icon: 'material-symbols:support', name: 'DOUBLE NECK SUPPORT' },
        { icon: 'game-icons:spring', name: 'REAR SHOCKERS' },
        { icon: 'ix:device-driver', name: 'CENTER LOCKING WITH BREAK JAMMING' },
        {
          icon: 'line-md:car-light',
          name: 'LED INDICATORS WITH NEW TRANSPERENT DESIGN',
        },
        {
          icon: 'ph:seat-fill',
          name: 'MACHINERY MADE WIDDER SEATS FOR BEST COMFORT',
        },
        {
          icon: 'eos-icons:performance',
          name: '10 MM WIRRING FOR BEST PERFORMANCE',
        },
        {
          icon: 'icon-park-solid:handle-round',
          name: 'BEST HANDLE CUTTING FOR EASY DRIVE',
        },
      ],
      specification: [
        {
          mileage: '100-150 Km (As per Battery Fittment)',
          batteryType: 'Lead Acid/Li-Ion',
          batteryWarranty: '1 To 3 Year (As Per Requirement),',
          motorAndController: '1100W/1250W',
          chargingTime: '6-8 Hours',
          sittingCapacity: '1 + 4 Person',
          brake: 'Brake Drum',
          speedometer: 'Digital',
          tyres: 'CEAT/Ralco',
          chassisWarranty: '1 Year',
          shockers: `31' Heavy Duty`,
          seat: 'Machinery Made Foam',
        },
      ],
      info: [
        'HEAVY DUTY CHASSIS & BODY',
        '5 COAT LONG LASTING PAINT',
        'UNIQUE RICH DESIGN',
        `HEAVY DUTY 31' SHOCKERS`,
        `MOBILE CHARGER`,
        `MOBILE HOLDER`,
        `DIGITAL METER`,
        `IN ROOF HITLON CLOTH`,
        `CAN GIVE MILEAGE UPTO 100 TO 150 KMS (AS PER BATTERY FITMENT)`,
        `HIGH PCKUP AND SPEED`,
        `DOUBLE NECK SUPPORT`,
        `REAR SHOCKERS`,
        `CENTER LOCKINGWITH BREAK JAMMING`,
        `GPS TRACKING (ON DEMAND)`,
        `FRONT MIRROR LIGHT`,
        `BATTERY WARRANTY UPTO 3 YEARS`,
        `FULL CHARGE IN 6 HOURS`,
        `LED INDICATOR WITH NEW DESIGN`,
        `MACHINERY MADE WIDER SEATS FOR BEST COMFORT`,
        `PURE 10MM WIRRING FOR BEST PERFORMANCE`,
        `BEST HANDLE CUTTING FOR EASY DRIVE`,
      ],
    },
    // commingSoon: true,
  },
  {
    name: 'Fateh Silver SS',
    image: '',
    featuredImage: '/images/silver ss/fateh-silver-ss.jpg',
    gallery: ['/images/silver ss/fateh-silver-ss-black.png',
      '/images/silver ss/fateh-silver-ss-green.png',
      '/images/silver ss/fateh-silver-ss-lightgreen.png',
      '/images/silver ss/fateh-silver-ss-purple.png',
      '/images/silver ss/fateh-silver-ss-red.png',
    ],
    description:
      'Built for businesses, this robust model is designed to handle heavy loads, making it ideal for vendors, small businesses, and logistics.',
    slug: 'fateh-silver-ss',
    features: {
      overview: [
        {
          icon: 'fluent:paint-brush-32-filled',
          name: 'PU PAINT WITH LONG LASTING 5 COAT',
        },
        {
          icon: 'fluent:wrench-screwdriver-32-filled',
          name: 'UNIQUE RICH DESIGN',
        },
        {
          icon: 'ic:baseline-electric-rickshaw',
          name: 'IN ROOF HITLON AND CLOTH',
        },
        { icon: 'material-symbols:speed', name: 'HIGH PICKUP AND SPEED' },
        { icon: 'material-symbols:support', name: 'DOUBLE NECK SUPPORT' },
        { icon: 'game-icons:spring', name: 'REAR SHOCKERS' },
        { icon: 'ix:device-driver', name: 'CENTER LOCKING WITH BREAK JAMMING' },
        {
          icon: 'line-md:car-light',
          name: 'LED INDICATORS WITH NEW TRANSPERENT DESIGN',
        },
        {
          icon: 'ph:seat-fill',
          name: 'MACHINERY MADE WIDDER SEATS FOR BEST COMFORT',
        },
        {
          icon: 'eos-icons:performance',
          name: '10 MM WIRRING FOR BEST PERFORMANCE',
        },
        {
          icon: 'icon-park-solid:handle-round',
          name: 'BEST HANDLE CUTTING FOR EASY DRIVE',
        },
      ],
      specification: [
        {
          mileage: '100-150 Km (As per Battery Fittment)',
          batteryType: 'Lead Acid/Li-Ion',
          batteryWarranty: '1 To 3 Year (As Per Requirement),',
          motorAndController: '1100W/1250W',
          chargingTime: '6-8 Hours',
          sittingCapacity: '1 + 4 Person',
          brake: 'Brake Drum',
          speedometer: 'Digital',
          tyres: 'CEAT/Ralco',
          chassisWarranty: '1 Year',
          shockers: `31' Heavy Duty`,
          seat: 'Machinery Made Foam',
        },
      ],
      info: [
        'HEAVY DUTY CHASSIS & BODY',
        '5 COAT LONG LASTING PAINT',
        'UNIQUE RICH DESIGN',
        `HEAVY DUTY 31' SHOCKERS`,
        `MOBILE CHARGER`,
        `MOBILE HOLDER`,
        `DIGITAL METER`,
        `IN ROOF HITLON CLOTH`,
        `CAN GIVE MILEAGE UPTO 100 TO 150 KMS (AS PER BATTERY FITMENT)`,
        `HIGH PCKUP AND SPEED`,
        `DOUBLE NECK SUPPORT`,
        `REAR SHOCKERS`,
        `CENTER LOCKINGWITH BREAK JAMMING`,
        `GPS TRACKING (ON DEMAND)`,
        `FRONT MIRROR LIGHT`,
        `BATTERY WARRANTY UPTO 3 YEARS`,
        `FULL CHARGE IN 6 HOURS`,
        `LED INDICATOR WITH NEW DESIGN`,
        `MACHINERY MADE WIDER SEATS FOR BEST COMFORT`,
        `PURE 10MM WIRRING FOR BEST PERFORMANCE`,
        `BEST HANDLE CUTTING FOR EASY DRIVE`,
      ],
    },
    // commingSoon: true,
  },
  {
    name: 'FatehEV Cargo(Loader)',
    image: '',
    featuredImage: '/images/products/product-3.webp',
    description:
      'Built for businesses, this robust model is designed to handle heavy loads, making it ideal for vendors, small businesses, and logistics.',
    slug: 'fatehev-garbage',
    features: {
      overview: [
        {
          icon: 'fluent:paint-brush-32-filled',
          name: 'PU PAINT WITH LONG LASTING 5 COAT',
        },
        {
          icon: 'fluent:wrench-screwdriver-32-filled',
          name: 'UNIQUE RICH DESIGN',
        },
        {
          icon: 'ic:baseline-electric-rickshaw',
          name: 'IN ROOF HITLON AND CLOTH',
        },
        { icon: 'material-symbols:speed', name: 'HIGH PICKUP AND SPEED' },
        { icon: 'material-symbols:support', name: 'DOUBLE NECK SUPPORT' },
        { icon: 'game-icons:spring', name: 'REAR SHOCKERS' },
        { icon: 'ix:device-driver', name: 'CENTER LOCKING WITH BREAK JAMMING' },
        {
          icon: 'line-md:car-light',
          name: 'LED INDICATORS WITH NEW TRANSPERENT DESIGN',
        },
        {
          icon: 'ph:seat-fill',
          name: 'MACHINERY MADE WIDDER SEATS FOR BEST COMFORT',
        },
        {
          icon: 'eos-icons:performance',
          name: '10 MM WIRRING FOR BEST PERFORMANCE',
        },
        {
          icon: 'icon-park-solid:handle-round',
          name: 'BEST HANDLE CUTTING FOR EASY DRIVE',
        },
      ],
      specification: [
        {
          mileage: '100-150 Km (As per Battery Fittment)',
          batteryType: 'Lead Acid/Li-Ion',
          batteryWarranty: '1 To 3 Year (As Per Requirement),',
          motorAndController: '1100W/1250W',
          chargingTime: '6-8 Hours',
          sittingCapacity: '1 + 4 Person',
          brake: 'Brake Drum',
          speedometer: 'Digital',
          tyres: 'CEAT/Ralco',
          chassisWarranty: '1 Year',
          shockers: `31' Heavy Duty`,
          seat: 'Machinery Made Foam',
        },
      ],
      info: [
        'HEAVY DUTY CHASSIS & BODY',
        '5 COAT LONG LASTING PAINT',
        'UNIQUE RICH DESIGN',
        `HEAVY DUTY 31' SHOCKERS`,
        `MOBILE CHARGER`,
        `MOBILE HOLDER`,
        `DIGITAL METER`,
        `IN ROOF HITLON CLOTH`,
        `CAN GIVE MILEAGE UPTO 100 TO 150 KMS (AS PER BATTERY FITMENT)`,
        `HIGH PCKUP AND SPEED`,
        `DOUBLE NECK SUPPORT`,
        `REAR SHOCKERS`,
        `CENTER LOCKINGWITH BREAK JAMMING`,
        `GPS TRACKING (ON DEMAND)`,
        `FRONT MIRROR LIGHT`,
        `BATTERY WARRANTY UPTO 3 YEARS`,
        `FULL CHARGE IN 6 HOURS`,
        `LED INDICATOR WITH NEW DESIGN`,
        `MACHINERY MADE WIDER SEATS FOR BEST COMFORT`,
        `PURE 10MM WIRRING FOR BEST PERFORMANCE`,
        `BEST HANDLE CUTTING FOR EASY DRIVE`,
      ],
    },
    commingSoon: true,
  },
  {
    name: 'Fateh Garbage Loader',
    image: '',
    featuredImage: '/images/products/product-3.webp',
    description:
      'Built for businesses, this robust model is designed to handle heavy loads, making it ideal for vendors, small businesses, and logistics.',
    slug: 'fatehev-garbage',
    features: {
      overview: [
        {
          icon: 'fluent:paint-brush-32-filled',
          name: 'PU PAINT WITH LONG LASTING 5 COAT',
        },
        {
          icon: 'fluent:wrench-screwdriver-32-filled',
          name: 'UNIQUE RICH DESIGN',
        },
        {
          icon: 'ic:baseline-electric-rickshaw',
          name: 'IN ROOF HITLON AND CLOTH',
        },
        { icon: 'material-symbols:speed', name: 'HIGH PICKUP AND SPEED' },
        { icon: 'material-symbols:support', name: 'DOUBLE NECK SUPPORT' },
        { icon: 'game-icons:spring', name: 'REAR SHOCKERS' },
        { icon: 'ix:device-driver', name: 'CENTER LOCKING WITH BREAK JAMMING' },
        {
          icon: 'line-md:car-light',
          name: 'LED INDICATORS WITH NEW TRANSPERENT DESIGN',
        },
        {
          icon: 'ph:seat-fill',
          name: 'MACHINERY MADE WIDDER SEATS FOR BEST COMFORT',
        },
        {
          icon: 'eos-icons:performance',
          name: '10 MM WIRRING FOR BEST PERFORMANCE',
        },
        {
          icon: 'icon-park-solid:handle-round',
          name: 'BEST HANDLE CUTTING FOR EASY DRIVE',
        },
      ],
      specification: [
        {
          mileage: '100-150 Km (As per Battery Fittment)',
          batteryType: 'Lead Acid/Li-Ion',
          batteryWarranty: '1 To 3 Year (As Per Requirement),',
          motorAndController: '1100W/1250W',
          chargingTime: '6-8 Hours',
          sittingCapacity: '1 + 4 Person',
          brake: 'Brake Drum',
          speedometer: 'Digital',
          tyres: 'CEAT/Ralco',
          chassisWarranty: '1 Year',
          shockers: `31' Heavy Duty`,
          seat: 'Machinery Made Foam',
        },
      ],
      info: [
        'HEAVY DUTY CHASSIS & BODY',
        '5 COAT LONG LASTING PAINT',
        'UNIQUE RICH DESIGN',
        `HEAVY DUTY 31' SHOCKERS`,
        `MOBILE CHARGER`,
        `MOBILE HOLDER`,
        `DIGITAL METER`,
        `IN ROOF HITLON CLOTH`,
        `CAN GIVE MILEAGE UPTO 100 TO 150 KMS (AS PER BATTERY FITMENT)`,
        `HIGH PCKUP AND SPEED`,
        `DOUBLE NECK SUPPORT`,
        `REAR SHOCKERS`,
        `CENTER LOCKINGWITH BREAK JAMMING`,
        `GPS TRACKING (ON DEMAND)`,
        `FRONT MIRROR LIGHT`,
        `BATTERY WARRANTY UPTO 3 YEARS`,
        `FULL CHARGE IN 6 HOURS`,
        `LED INDICATOR WITH NEW DESIGN`,
        `MACHINERY MADE WIDER SEATS FOR BEST COMFORT`,
        `PURE 10MM WIRRING FOR BEST PERFORMANCE`,
        `BEST HANDLE CUTTING FOR EASY DRIVE`,
      ],
    },
    commingSoon: true,
  },
];
